// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kijdcyebbvbsjmhzutlf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpamRjeWViYnZic2ptaHp1dGxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDM2OTAsImV4cCI6MjA2NTU3OTY5MH0.6S_oA5XEy9ODnL0r__i6PYoJ-dFDoJpXUR3udSaPaMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);